### PR TITLE
DNM: Testing ut in zuul for cisco.asa

### PR DESCRIPTION
**Pull request by GomathiselviS**
Depends-on: https://github.com/ansible/ansible-zuul-jobs/pull/430

### CODE REVIEW

**Comment by GomathiselviS** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by justjais** [comment]
@GomathiselviS there seems to be an integration test failure from asa_ogs module. I'm planning to update the given module to use the rm_prototype code. I'll be raising the PR with the update asap and I'll fix the observed integration failure with the same.

**Comment by pabelanger** [comment]
This can actually be closed now, we fixed both unit tests and integration tests in https://github.com/ansible-collections/cisco.asa/pull/25

**Comment by justjais** [comment]
@pabelanger ah ok.. thanks for the confirmation. Closing the issue as the issue is fixed with #25

**Pull request closed without merging**
