### PR TITLE
Sanity tests: copy ignore-2.13.txt to ignore-2.14.txt

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
https://github.com/ansible-collections/news-for-maintainers/issues/13
Depends-On: https://github.com/ansible-collections/cisco.asa/pull/159
Dear maintainers,

I'd like to ask you to track the news-for-maintainers themselves in the future if possible

Thanks!

### CODE REVIEW

**Comment by Andersson007** [comment]
there are unrelated CI errors, could anyone from maintainers take a look?

**Comment by Andersson007** [comment]
depends on https://github.com/ansible-collections/cisco.asa/pull/159

**Comment by KB-perByte** [comment]
recheck

**Review by KB-perByte — APPROVED** [review]

**Comment by gundalow** [comment]
command: `source ~/venv/bin/activate; ansible-test sanity --requirements --python 3.8 --docker -v`
That might be caused by having `--requirements` AND `--docker`
Even if not, we should remove `--requirments` as the Docker Containers include specific versions of what's needed

**Comment by gundalow** [comment]
If you look at the raw logs seems like there are extra things that need fixing

```
2022-04-27 14:34:07.324382 | controller | ERROR: Found 5 validate-modules issue(s) which need to be resolved:
2022-04-27 14:34:07.324456 | controller | ERROR: plugins/cliconf/asa.py:0:0: invalid-documentation: DOCUMENTATION.author: Invalid author for dictionary value @ data['author']. Got 'Ansible Security Team'
2022-04-27 14:34:07.324517 | controller | ERROR: plugins/cliconf/asa.py:0:0: invalid-documentation: DOCUMENTATION.cliconf: extra keys not allowed @ data['cliconf']. Got 'asa'
2022-04-27 14:34:07.324585 | controller | ERROR: plugins/cliconf/asa.py:0:0: invalid-documentation: DOCUMENTATION.name: required key not provided @ data['name']. Got None
2022-04-27 14:34:07.324654 | controller | ERROR: plugins/cliconf/asa.py:0:0: parameter-list-no-elements: DOCUMENTATION.options.config_commands: Argument defines type as list but elements is not defined for dictionary value @ data['options']['config_commands']. Got {'description': ['Specifies a list of commands that can make configuration changes to the target device.', 'When `ansible_network_single_user_mode` is enabled, if a command sent to the device is present in this list, the existing cache is invalidated.'], 'version_added': '2.0.0', 'type': 'list', 'default': [], 'vars': [{'name': 'ansible_asa_config_commands'}], 'version_added_collection': 'cisco.asa'}
2022-04-27 14:34:07.324713 | controller | ERROR: plugins/modules/asa_facts.py:0:0: invalid-documentation-markup: DOCUMENTATION.options.gather_network_resources.description: Directive "M(!)" must contain a FQCN for dictionary value @ data['options']['gather_network_resources']['description']. Got ["When supplied, this argument will restrict the facts collected to a given subset. Possible values for this argument include all and the resources like interfaces, vlans etc. Can specify a list of values to include a larger subset. Values can also be used with an initial C(M(!)) to specify that a specific subset should not be collected. Valid subsets are 'all', 'acls', 'ogs'."]
202
```

The last one may need adding to `ignore.txt`

**Comment by justjais** [comment]
recheck

**Comment by justjais** [comment]
Changes were merged via https://github.com/ansible-collections/cisco.asa/pull/158. Closing the PR

**Pull request closed without merging**
