### PR TITLE
Fix TypeError: argument of type 'NoneType' is not iterable in service-group

### PR DESCRIPTION
**Pull request by lvrfrc87**
##### SUMMARY
`TypeError: argument of type 'NoneType' is not iterable in service-group` when service-object not existing in ASA V. 9.6(3)17 <context>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
asa_og.py

##### ADDITIONAL INFORMATION
```
{
    "module_stdout": "",
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-7917vsjauk24/ansible-tmp-1599135052.5277274-179017891288941/AnsiballZ_asa_og.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-7917vsjauk24/ansible-tmp-1599135052.5277274-179017891288941/AnsiballZ_asa_og.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-7917vsjauk24/ansible-tmp-1599135052.5277274-179017891288941/AnsiballZ_asa_og.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.asa.asa_og', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_asa_og_payload_qfhj60mq/ansible_asa_og_payload.zip/ansible/modules/network/asa/asa_og.py\", line 801, in <module>\n  File \"/tmp/ansible_asa_og_payload_qfhj60mq/ansible_asa_og_payload.zip/ansible/modules/network/asa/asa_og.py\", line 788, in main\n  File \"/tmp/ansible_asa_og_payload_qfhj60mq/ansible_asa_og_payload.zip/ansible/modules/network/asa/asa_og.py\", line 735, in map_obj_to_commands\n  File \"/tmp/ansible_asa_og_payload_qfhj60mq/ansible_asa_og_payload.zip/ansible/modules/network/asa/asa_og.py\", line 602, in present\nTypeError: argument of type 'NoneType' is not iterable\n",
    "exception": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-7917vsjauk24/ansible-tmp-1599135052.5277274-179017891288941/AnsiballZ_asa_og.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-7917vsjauk24/ansible-tmp-1599135052.5277274-179017891288941/AnsiballZ_asa_og.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-7917vsjauk24/ansible-tmp-1599135052.5277274-179017891288941/AnsiballZ_asa_og.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.asa.asa_og', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_asa_og_payload_qfhj60mq/ansible_asa_og_payload.zip/ansible/modules/network/asa/asa_og.py\", line 801, in <module>\n  File \"/tmp/ansible_asa_og_payload_qfhj60mq/ansible_asa_og_payload.zip/ansible/modules/network/asa/asa_og.py\", line 788, in main\n  File \"/tmp/ansible_asa_og_payload_qfhj60mq/ansible_asa_og_payload.zip/ansible/modules/network/asa/asa_og.py\", line 735, in map_obj_to_commands\n  File \"/tmp/ansible_asa_og_payload_qfhj60mq/ansible_asa_og_payload.zip/ansible/modules/network/asa/asa_og.py\", line 602, in present\nTypeError: argument of type 'NoneType' is not iterable\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1,
    "_ansible_no_log": false,
    "changed": false,
    "item": {
        "name": "ftp_svc",
        "description": "GNS-39102 - Infosec Security Tools",
        "service_cfg": [
            "tcp destination eq ftp",
            "tcp destination eq ftp-data"
        ]
    },
    "ansible_loop_var": "item",
    "_ansible_item_label": {
        "name": "ftp_svc",
        "description": "GNS-39102 - Infosec Security Tools",
        "service_cfg": [
            "tcp destination eq ftp",
            "tcp destination eq ftp-data"
        ]
    }
}
```

### CODE REVIEW

**Review by justjais — APPROVED** [review]

**Comment by lvrfrc87** [comment]
@justjais Any chance we can have this PR merged?

**Comment by justjais** [comment]
@lvrfrc87 yes, I've approved the changes but was waiting on the tests to turn green. Can you please look into the failures and fix and once the tests start to pass I'll gate it to get merged.

**Comment by lvrfrc87** [comment]
@justjais I get error regarding tox lint check which says that `asa_og.py` needs to be reformatted. I cannot though find anywhere which lines should be changed

**Comment by justjais** [comment]
@lvrfrc87 you need to run `tox -e black` to format the files as expected and that should resolve the failures, which in your case is `asa_og` file, ref:
```
2021-08-09 10:19:42.354423 | centos-8 | would reformat plugins/modules/asa_og.py
2021-08-09 10:19:42.388454 | centos-8 | plugins/modules/asa_ogs.py already well formatted, good job.
```
from [log](https://dashboard.zuul.ansible.com/t/ansible/build/f8dbc9345bd7445aafc1f32e29d219ac)
ref: [tox](https://github.com/ansible-collections/cisco.asa/blob/main/tox.ini)

**Comment by lvrfrc87** [comment]
@justjais here we are :)

**Pull request merged**
