### PR TITLE
Add support for single_user_mode

### PR DESCRIPTION
**Pull request by NilashishC**
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>
Depends-On: https://github.com/ansible-collections/cisco.asa/pull/90

##### SUMMARY
- Targets ansible-collections/ansible.netcommon#73
- Add support for ansible_single_user_mode option added in network_cli.
- Re-use device_info dictionary for every session.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
cliconf/asa.py
terminal/asa.py

### CODE REVIEW

**Comment by justjais** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Review by justjais — APPROVED** [review]

**Comment by NilashishC** [comment]
https://github.com/ansible-collections/ansible.netcommon/pull/180/ is breaking unit tests. We need to update the imports.

**Pull request merged**
